//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Goethe.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Goethe.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mixed inflection of the adjective {0} with the indefinite article &apos;ein&apos; or with pronouns like &apos;kein&apos; and &apos;mein&apos;.
        /// </summary>
        public static string Adj_MixedInflection_Description {
            get {
                return ResourceManager.GetString("Adj_MixedInflection_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using {0} as predicative.
        /// </summary>
        public static string Adj_Predicative_Description {
            get {
                return ResourceManager.GetString("Adj_Predicative_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The strong inflection of {0} without articles or pronouns.
        /// </summary>
        public static string Adj_StrongInflection_Description {
            get {
                return ResourceManager.GetString("Adj_StrongInflection_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The weak inflection of the adjective {0} with the definite article &apos;der&apos; or with pronouns like &apos;dieser&apos; and &apos;jener&apos;.
        /// </summary>
        public static string Adj_WeakInflection_Description {
            get {
                return ResourceManager.GetString("Adj_WeakInflection_Description", resourceCulture);
            }
        }
    }
}
